export const airports = [
  {
    airport_name: "Indira Gandhi International Airport",
    source_IATA: "DEL",
    source_gps: "VIDP",
    source_lat: 28.5665,
    source_lon: 77.103104,
  },
  {
    airport_name: "Chhatrapati Shivaji International Airport",
    source_IATA: "BOM",
    source_gps: "VABB",
    source_lat: 19.088699,
    source_lon: 72.867897,
  },
  {
    airport_name: "Kempegowda International Airport",
    source_IATA: "BLR",
    source_gps: "VOBL",
    source_lat: 13.197900,
    source_lon: 77.706299,
  },
  {
    airport_name: "Chennai International Airport",
    source_IATA: "MAA",
    source_gps: "VOMM",
    source_lat: 12.990005,
    source_lon: 80.169296,
  },
  {
    airport_name: "Dabolim Airport",
    source_IATA: "GOI",
    source_gps: "VOGO",
    source_lat: 15.380800,
    source_lon: 73.831398,
  },
  {
    airport_name: "Cochin International Airport",
    source_IATA: "COK",
    source_gps: "VOCI",
    source_lat: 10.152000,
    source_lon: 76.401901,
  },
  {
    airport_name: "Jaipur International Airport",
    source_IATA: "JAI",
    source_gps: "VIJP",
    source_lat: 26.8242,
    source_lon: 75.8122,
  },
  {
    airport_name: "Rajiv Gandhi International Airport",
    source_IATA: "HYD",
    source_gps: "VOHS",
    source_lat: 17.2313,
    source_lon: 78.4294,
  },
  {
    airport_name: "Netaji Subhash Chandra Bose International Airport",
    source_IATA: "CCU",
    source_gps: "VECC",
    source_lat: 22.6547,
    source_lon: 88.4467,
  },
  {
    airport_name: "Sardar Vallabhbhai Patel International Airport",
    source_IATA: "AMD",
    source_gps: "VAAH",
    source_lat: 23.0732,
    source_lon: 72.6347,
  },
];
