// export const NATIONALITIES = [
//   "India", "United States", "Canada", "Australia", "United Kingdom",
//   "Germany", "France", "Italy", "Spain", "Brazil", "Japan", "China",
//   "South Korea", "Russia", "Mexico", "Singapore", "South Africa", "New Zealand",
//   "UAE", "Saudi Arabia", "Pakistan", "Nepal", "Bangladesh", "Sri Lanka", "Indonesia",
//   "Thailand", "Malaysia", "Vietnam", "Philippines", "Turkey", "Egypt", "Argentina",
//   "Colombia", "Chile", "Norway", "Sweden", "Denmark", "Netherlands", "Belgium",
//   "Switzerland", "Austria", "Finland", "Ireland", "Poland", "Portugal", "Czech Republic"
// ];

// export const COUNTRY_CODES = [
//   { label: "+91 (India)", value: "+91" },
//   { label: "+1 (USA)", value: "+1" },
//   { label: "+44 (UK)", value: "+44" },
//   { label: "+61 (Australia)", value: "+61" },
//   { label: "+81 (Japan)", value: "+81" },
//   { label: "+49 (Germany)", value: "+49" },
//   { label: "+33 (France)", value: "+33" },
//   { label: "+86 (China)", value: "+86" },
//   { label: "+971 (UAE)", value: "+971" },
//   { label: "+92 (Pakistan)", value: "+92" },
//   { label: "+880 (Bangladesh)", value: "+880" },
//   { label: "+94 (Sri Lanka)", value: "+94" }
//   // Add more as needed
// ];

export const NATIONALITIES = [
  "Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica",
  "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas",
  "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan",
  "Bolivia, Plurinational State of", "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina",
  "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam",
  "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands",
  "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands",
  "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica",
  "Croatia", "Cuba", "Curaçao", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
  "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia",
  "Eswatini", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France",
  "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala",
  "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands",
  "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of",
  "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan",
  "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait",
  "Kyrgyzstan", "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
  "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia", "Maldives",
  "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
  "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montenegro",
  "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
  "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "North Macedonia",
  "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Palestine, State of", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico",
  "Qatar", "Réunion", "Romania", "Russian Federation", "Rwanda", "Saint Barthélemy", "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin (French part)", "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
  "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten (Dutch part)", "Slovakia",
  "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands",
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen", "Sweden",
  "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of",
  "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
  "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela, Bolivarian Republic of", "Viet Nam", "Western Sahara",
  "Yemen", "Zambia", "Zimbabwe"
];

export const COUNTRY_CODES = [
  { label: "Argentina (+54)", value: "+54" },
  { label: "Australia (+61)", value: "+61" },
  { label: "Austria (+43)", value: "+43" },
  { label: "Bangladesh (+880)", value: "+880" },
  { label: "Belgium (+32)", value: "+32" },
  { label: "Brazil (+55)", value: "+55" },
  { label: "Canada (+1)", value: "+1" },
  { label: "Chile (+56)", value: "+56" },
  { label: "China (+86)", value: "+86" },
  { label: "Colombia (+57)", value: "+57" },
  { label: "Czech Republic (+420)", value: "+420" },
  { label: "Denmark (+45)", value: "+45" },
  { label: "Egypt (+20)", value: "+20" },
  { label: "Finland (+358)", value: "+358" },
  { label: "France (+33)", value: "+33" },
  { label: "Germany (+49)", value: "+49" },
  { label: "India (+91)", value: "+91" },
  { label: "Ireland (+353)", value: "+353" },
  { label: "Italy (+39)", value: "+39" },
  { label: "Japan (+81)", value: "+81" },
  { label: "Mexico (+52)", value: "+52" },
  { label: "Netherlands (+31)", value: "+31" },
  { label: "New Zealand (+64)", value: "+64" },
  { label: "Norway (+47)", value: "+47" },
  { label: "Pakistan (+92)", value: "+92" },
  { label: "Philippines (+63)", value: "+63" },
  { label: "Poland (+48)", value: "+48" },
  { label: "Portugal (+351)", value: "+351" },
  { label: "Russia (+7)", value: "+7" },
  { label: "Saudi Arabia (+966)", value: "+966" },
  { label: "Singapore (+65)", value: "+65" },
  { label: "South Africa (+27)", value: "+27" },
  { label: "South Korea (+82)", value: "+82" },
  { label: "Spain (+34)", value: "+34" },
  { label: "Sri Lanka (+94)", value: "+94" },
  { label: "Sweden (+46)", value: "+46" },
  { label: "Switzerland (+41)", value: "+41" },
  { label: "Thailand (+66)", value: "+66" },
  { label: "Turkey (+90)", value: "+90" },
  { label: "UAE (+971)", value: "+971" },
  { label: "UK (+44)", value: "+44" },
  { label: "USA (+1)", value: "+1" },
  { label: "Vietnam (+84)", value: "+84" }
];
